vich_uploader:
    db_driver: orm
    mappings:
        identity_documents:
            uri_prefix: '/identity_documents'
            upload_destination: '%identity_documents_dir%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
