version: "3.5"

services:
    nginx:
        build:
            context: ./infra
            dockerfile: nginx.docker
        volumes:
            - .:/app
        environment:
            APP_ENV: dev
        depends_on:
            - php-fpm
        ports:
            - "80:80"

    php-fpm:
        build:
            context: ./infra
            dockerfile: php-fpm.docker
        volumes:
            - .:/app
            - composer:/root/.composer/cache
        environment:
            APP_ENV: dev
        depends_on:
            - postgres

    waiting-nodejs:
        image: node:10.21-jessie
        volumes:
            - .:/app
        working_dir: /app
        tty: true

    postgres:
        image: postgres:11.2-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: blog
        ports:
            - "54321:5432"

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8082:8025"
volumes:
    postgres:
    composer: