version: "3.5"

services:
    nginx:
        build:
            context: ./infra
            dockerfile: nginx.docker
        volumes:
            - .:/app
        environment:
            APP_ENV: dev
        depends_on:
            - php-fpm
        ports:
            - "80:80"

    php-fpm:
        build:
            context: ./infra
            dockerfile: php-fpm.docker
        volumes:
            - .:/app
            - composer:/root/.composer/cache
        environment:
            APP_ENV: dev
        depends_on:
            - postgres

    postgres:
        image: postgres:11.2-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: blog
        ports:
            - "54321:5432"

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8082:8025"
volumes:
    postgres:
    composer: